### ISSUE TITLE
原生模拟器(api 28)虚拟机检测错误,loadSO点击崩溃

### ISSUE THREAD

**Issue by lydlovezjr** [lamster2018/EasyProtector#13]
emulatorInfo:
ceshi start|1.0.0.0|sdk_gphone_x86-userdebug|goldfish_x86||2:cpu:/
    1:cpuacct:/uid_10085/pid_6675
    |end

2018-10-19 15:40:30.140 6011-6160/com.google.android.gms E/CheckinRequestProcessor: CheckinNowTaskTag : Checkin failed: https://android.clients.google.com/checkin (fragment #0): java.net.ConnectException: Failed to connect to android.clients.google.com/64.233.189.101:443
    java.net.ConnectException: Failed to connect to android.clients.google.com/64.233.189.101:443
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
        at nmb.a(:com.google.android.gms@12862026@12.8.62 (040700-199405334):23)
        at nmb.a(:com.google.android.gms@12862026@12.8.62 (040700-199405334):273)
        at com.google.android.gms.checkin.CheckinChimeraService.a(:com.google.android.gms@12862026@12.8.62 (040700-199405334):167)
        at nlw.run(:com.google.android.gms@12862026@12.8.62 (040700-199405334):2)
        at pmy.run(:com.google.android.gms@12862026@12.8.62 (040700-199405334):24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at pta.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)

**Comment by lamster2018** [comment]
恩，我刚刚自查了，原生模拟器（api 28），你应该是用的AS的debug模式启动的吧？trace_id大于1000了，所以直接自杀了。
```
10-19 16:06:54.212  5123  5123 I System.out: ceshi start|1.0.0.0|sdk_gphone_x86-user|goldfish_x86||2:cpu:/
10-19 16:06:54.212  5123  5123 D ceshi   : JNI on load...
10-19 16:06:54.212  5123  5123 D ceshi   : ptrace myself...
10-19 16:06:54.218  5123  5337 D ceshi   : traceId:1868
10-19 16:06:54.218  5123  5337 D ceshi   : I was be traced...trace pid:1868
```
log代码
adb logcat | grep ceshi

这部分检测文件在jni下的antitrace.cpp文件里
如果你是打包出来安装运行的话，没有tracer，可以正常loadSo的

**Comment by kyriej** [comment]
@lamster2018 为什么打包出来也是会执行exit(0)
