### ISSUE TITLE
Error:Execution failed for task ':app:processDebugManifest'. > Manifest merg failed with multiple errors, see logs

### ISSUE THREAD

**Issue by mixin716** [lamster2018/EasyProtector#9]
引入包之后报这个错误，是不是用到了fileprovider

**Comment by lamster2018** [comment]
没有用到fileProvider，provider都需要在清单里注册的，你可以查看清单。
具体问题，能看下完整log么？

**Comment by mixin716** [comment]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugManifest'.
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Manifest merger failed with multiple  errors, see logs
	at com.android.builder.core.AndroidBuilder..mergeManifestsForApplication(AndroidBuilder.java:524)
	at com.android.build.gradle.tasks.MergeManifests.doFullTaskAction(MergeManifests.java:143)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
这个大概是主要日志，不管是直接implementation还是下载下来jar包导入都是报这个错误，能帮忙看下吗

**Comment by lamster2018** [comment]
所以能说下这笔问题最后是什么原因么？
